import type { HomeData } from "./types";
const img = (id: string, alt: string) => ({ url: `https://images.unsplash.com/${id}?auto=format&fit=crop&w=2200&q=85`, alt });
export const demoHomeData: HomeData = {
 brand: { name: "VINSKAPE", tagline: "Crafting Spaces. Defining Lifestyles.", contact: { phone: "+91 98765 43210", whatsapp: "919876543210", whatsappMessage: "Hi Vinskape team, I need a quotation for interior design.", email: "studio@vinskape.in", address: "Kochi, Kerala · India", hours: "Mon–Sat, 10:00–18:30" } },
 navigation: [{label:"Home"},{label:"About"},{label:"Gallery",children:[{label:"Ongoing Projects"},{label:"Completed Projects"}]},{label:"Services",children:[{label:"Residential",children:[{label:"Budget Homes"},{label:"Villas"}]},{label:"Commercial",children:[{label:"Shops"},{label:"Restaurants"}]},{label:"Industrial",children:[{label:"Offices"}]}]},{label:"Our Dealers"},{label:"Portfolio",children:[{label:"Living Room"},{label:"Hall"},{label:"Kitchen"},{label:"Bedroom"},{label:"Bathroom"}]},{label:"Testimonials"},{label:"Contact",featured:true}],
 heroSlides: [
  {id:"welcome",eyebrow:"WELCOME TO VINSKAPE",heading:"Crafting Spaces.\nDefining Lifestyles.",description:"Transforming homes, workplaces and commercial environments into thoughtfully designed spaces that feel distinctly yours.",image:img("photo-1618221195710-dd6b41faaea6","Warm modern living room"),primaryCta:"Explore Our Work",secondaryCta:"Begin a conversation"},
  {id:"residential",eyebrow:"RESIDENTIAL INTERIORS",heading:"Interiors Designed\nAround You",description:"Elegant apartments and sophisticated villas, balanced for beauty, comfort and the rhythms of everyday life.",image:img("photo-1600607687920-4e2a09cf159d","Contemporary home interior"),primaryCta:"Discover Residential"},
  {id:"timeless",eyebrow:"TIMELESS DESIGN",heading:"Where Elegance\nMeets Function",description:"Refined details, intelligent planning and materials chosen to grow more beautiful with time.",image:img("photo-1600566753190-17f0baa2a6c3","Minimal kitchen dining interior"),primaryCta:"View Our Portfolio"},
  {id:"commercial",eyebrow:"COMMERCIAL SPACES",heading:"Spaces That Build\nExperiences",description:"Memorable environments that strengthen your brand and elevate each customer interaction.",image:img("photo-1511818966892-d7d671e672a2","Warm restaurant interior"),primaryCta:"Explore Commercial"},
  {id:"story",eyebrow:"YOUR SPACE. YOUR STORY.",heading:"Let’s Create Something\nExtraordinary",description:"Tell us about your space and let our design team turn your vision into a beautifully crafted reality.",image:img("photo-1616486338812-3dadae4b4ace","Sophisticated bedroom interior"),primaryCta:"Start Your Project"}
 ],
 introduction:{eyebrow:"ABOUT VINSKAPE",heading:"Spaces designed to feel like yours.",description:"Vinskape brings architectural thinking to the intimate details of everyday living. We make rooms that work beautifully, and feel quietly personal.",image:img("photo-1600585154340-be6161a56a0c","Modern Vinskape residence"),cta:{text:"Discover our approach",action:"#"},statistics:[{value:"10+",label:"Years of design experience"},{value:"250+",label:"Spaces crafted"},{value:"100%",label:"Client-focused design"}]},
 services:[{name:"Residential",description:"Homes with a quietly luxurious sense of ease.",items:["Budget Homes","Villas"],image:img("photo-1600210492486-724fe5c67fb0","Residential interior")},{name:"Commercial",description:"Spaces that invite customers to stay, notice and return.",items:["Shops","Restaurants"],image:img("photo-1497366754035-f200968a6e72","Commercial interior")},{name:"Industrial",description:"Workplaces calibrated for people, purpose and performance.",items:["Offices","Studios"],image:img("photo-1497366216548-37526070297c","Office interior")}],
 projects:[{name:"Contemporary Residence",category:"Residential",location:"Kochi",description:"Natural stone, smoked oak and a calm, open plan.",status:"DEMO PROJECT",image:img("photo-1600585154340-be6161a56a0c","Contemporary residence")},{name:"Urban Villa",category:"Residential",location:"Bengaluru",description:"A modern retreat built around daylight and gathering.",status:"DEMO PROJECT",image:img("photo-1615874694520-474822394e73","Urban villa")},{name:"Modern Café",category:"Commercial",location:"Kochi",description:"Textured materiality for lingering conversations.",status:"DEMO PROJECT",image:img("photo-1517248135467-4c7edcad34c4","Modern cafe")},{name:"Boutique Retail",category:"Commercial",location:"Mumbai",description:"A considered journey through product and space.",status:"DEMO PROJECT",image:img("photo-1441986300917-64674bd600d8","Boutique retail interior")}],
 portfolio:["Living Room","Hall","Kitchen","Bedroom","Bathroom","Dining","Office","Commercial"].map((name,i)=>({name,image:img(["photo-1618221195710-dd6b41faaea6","photo-1616486338812-3dadae4b4ace","photo-1600566753190-17f0baa2a6c3","photo-1600210492486-724fe5c67fb0"][i%4],`${name} interior`)})),
 testimonials:[{quote:"The team listened closely, then made every room feel more considered than we imagined possible.",name:"Demo Client",place:"Kochi",project:"Contemporary Residence"},{quote:"The process was grounded, thoughtful and exceptionally clear from the first sketch to the final detail.",name:"Demo Client",place:"Bengaluru",project:"Urban Villa"}]
};
