"use client";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import type { HeroSlide } from "@/sanity/types";
import Link from "next/link";
export function Hero({ slides }: { slides: HeroSlide[] }) { const validSlides=slides.filter(s=>typeof s.image?.url==="string"&&s.image.url.trim().length>0); const [active,setActive]=useState(0); const [paused,setPaused]=useState(false); const touch=useRef(0); const next=()=>setActive(i=>(i+1)%validSlides.length); const prev=()=>setActive(i=>(i-1+validSlides.length)%validSlides.length);
 useEffect(()=>{setActive(i=>Math.min(i,Math.max(validSlides.length-1,0)))},[validSlides.length]); useEffect(()=>{ if(paused||validSlides.length<2) return; const timer=window.setInterval(next,5600); return()=>clearInterval(timer); },[paused,validSlides.length]); useEffect(()=>{const key=(e:KeyboardEvent)=>e.key==="ArrowRight"?next():e.key==="ArrowLeft"?prev():undefined; window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[validSlides.length]); if(!validSlides.length)return <section className="hero fallback"><p>VINSKAPE</p><h1>Thoughtful spaces, waiting to be told.</h1></section>;
 const slide=validSlides[active]; return <section className="hero" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(e.changedTouches[0].clientX-touch.current>40)prev();if(touch.current-e.changedTouches[0].clientX>40)next();}}>
  {validSlides.map((s,i)=><Image key={s.id} src={s.image.url} alt={s.image.alt || ""} fill priority={i===0} sizes="100vw" className={`hero-image ${i===active?"show":""}`} />)}<div className="hero-shade" />
  <div className="hero-content" key={slide.id}><p className="eyebrow">{slide.eyebrow}</p><h1>{slide.heading.split("\n").map(x=><span key={x}>{x}</span>)}</h1><p className="hero-copy">{slide.description}</p><div className="hero-actions"><Link href="/portfolio" className="button light">{slide.primaryCta}<span>↗</span></Link>{slide.secondaryCta&&<Link href="/contact" className="text-button">{slide.secondaryCta} <span>→</span></Link>}</div></div>
  <div className="hero-bottom"><span>0{active+1} / 0{validSlides.length}</span><div className="progress">{validSlides.map((s,i)=><button aria-label={`Show slide ${i+1}`} onClick={()=>setActive(i)} key={s.id}><i className={i===active?"current":""}/></button>)}</div><div className="arrows"><button aria-label="Previous slide" onClick={prev}>←</button><button aria-label="Next slide" onClick={next}>→</button></div></div>
 </section> }
