import Image from "next/image";
import { Hero } from "./Hero";
import { Navigation } from "../layout/Navigation";
import { WhatsApp } from "../layout/WhatsApp";
import type { HomeData } from "@/sanity/types";
const Arrow=()=> <span className="arrow">→</span>;
export function Home({data}:{data:HomeData}) { const c=data.brand.contact; const intro=data.introduction; const ctaImage=data.heroSlides.at(-1)?.image ?? data.projects[0]?.image; return <main><Navigation brand={data.brand.name} items={data.navigation}/><Hero slides={data.heroSlides}/>
 <section className="intro shell"><div className="intro-image"><Image src={intro.image.url} alt={intro.image.alt} fill sizes="(max-width: 800px) 100vw, 42vw"/></div><div className="intro-copy"><p className="eyebrow dark">{intro.eyebrow}</p><h2>{intro.heading}</h2><p>{intro.description}</p><button className="link-button">{intro.cta.text} <Arrow/></button><div className="metrics">{intro.statistics.map(stat=>{const match=stat.value.match(/^(\d+)(.*)$/);return <div key={stat.label}><strong>{match?.[1] ?? stat.value}<span>{match?.[2]}</span></strong><small>{stat.label}</small></div>})}</div><p className="demo-note">Demo metrics — to be confirmed with Vinskape.</p></div></section>
 <section className="services shell"><div className="section-head"><p className="eyebrow dark">WHAT WE SHAPE</p><h2>Designing every kind<br/>of <em>space.</em></h2><p>From the first idea to the final finish, every project begins with a deeper understanding of how it should feel.</p></div><div className="service-grid">{data.services.map((s,i)=><article className="service-card" key={s.name}><div className="card-image"><Image src={s.image.url} alt={s.image.alt} fill sizes="(max-width: 800px) 100vw, 33vw"/></div><p>0{i+1}</p><h3>{s.name}</h3><p className="service-desc">{s.description}</p><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul><button className="round-arrow" aria-label={`Explore ${s.name}`}>↗</button></article>)}</div></section>
 <section className="projects"><div className="shell"><div className="project-heading"><p className="eyebrow">SELECTED SPACES</p><h2>Stories told<br/>through <em>space.</em></h2><button className="button outline">View all projects <Arrow/></button></div><div className="project-grid">{data.projects.map((p,i)=><article key={p.name} className={`project project-${i}`}><Image src={p.image.url} alt={p.image.alt} fill sizes="(max-width: 800px) 100vw, 50vw"/><div><p>{p.status} · {p.category}</p><h3>{p.name}</h3><span>{p.location} <Arrow/></span></div></article>)}</div></div></section>
 <section className="portfolio shell"><div className="section-head"><p className="eyebrow dark">EXPLORE THE DETAILS</p><h2>A place for every<br/><em>way of living.</em></h2></div><div className="portfolio-grid">{data.portfolio.map((p,i)=><button key={p.name} className={`portfolio-item tile-${i}`}><Image src={p.image.url} alt={p.image.alt} fill sizes="(max-width: 800px) 50vw, 25vw"/><span>{p.name}<Arrow/></span></button>)}</div></section>
 <section className="why"><div className="shell why-inner"><div><p className="eyebrow">THE VINSKAPE WAY</p><h2>Designed with purpose.<br/><em>Crafted with precision.</em></h2></div><div className="benefits">{[["01","Thoughtful design","Every space starts with listening to the life that will unfold within it."],["02","Functional luxury","Beauty and practicality are never separate ideas."],["03","Attention to detail","Light, proportion, material and finish, considered as one."],["04","End-to-end approach","From early concept through to the smallest finishing touch."]].map(x=><div key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
 <section className="partners shell"><p className="eyebrow dark">OUR TRUSTED PARTNERS</p><div><h2>Good work is never<br/>done <em>alone.</em></h2><p>We collaborate with carefully chosen makers and suppliers. Partner identities shown here are neutral demo placeholders.</p></div><div className="logos">{["FORM","ATELIER","MATERIA","NORTHLINE","STUDIO 06"].map(x=><span key={x}>{x}</span>)}</div></section>
 <section className="testimonials shell"><p className="eyebrow dark">CLIENT NOTES</p><div className="quote-mark">“</div>{data.testimonials.map((t,i)=><article key={t.name+i} className={i?"hidden-quote":""}><blockquote>{t.quote}</blockquote><p><strong>{t.name}</strong> · {t.place}<br/><small>{t.project} — Demo testimonial</small></p></article>)}</section>
 <section className="cta">{ctaImage?.url&&<Image src={ctaImage.url} alt={ctaImage.alt || ""} fill sizes="100vw"/>}<div className="cta-overlay"/><div className="shell cta-content"><p className="eyebrow">BEGIN WITH A CONVERSATION</p><h2>Your space deserves more<br/>than <em>ordinary.</em></h2><p>Let’s turn your ideas into a space you’ll love to live, work and experience.</p><button className="button light">Start a conversation <Arrow/></button></div></section>
 <section className="contact shell"><p className="eyebrow dark">CONTACT VINSKAPE</p><h2>Bring us the beginning<br/>of an <em>idea.</em></h2><div className="contact-grid"><a href={`tel:${c.phone}`}>{c.phone}</a><a href={`mailto:${c.email}`}>{c.email}</a><span>{c.address}</span><span>{c.hours}</span></div></section>
 <footer><div className="shell footer-top"><div><h2>{data.brand.name}</h2><p>{data.brand.tagline}</p></div><div className="footer-links"><span>Company</span><span>Services</span><span>Portfolio</span><span>Contact</span></div><p className="footer-contact">{c.phone}<br/>{c.email}</p></div><div className="shell footer-bottom"><span>© 2026 Vinskape. All rights reserved.</span><span>Instagram · Facebook · LinkedIn</span></div></footer><WhatsApp number={c.whatsapp} message={c.whatsappMessage}/></main> }
